/**
 * app.js - Logic for OSINT Dashboard
 * Handles: Data fetching, Auto-refresh, Map rendering, Charting, and DOM updates.
 */

// Configuration
const DATA_URL = 'data.json'; // This file will be generated by our Python script/GitHub Action
const REFRESH_INTERVAL = 60000; // 1 minute in milliseconds
const NEW_ARTICLE_THRESHOLD_MINS = 30;

let map = null;
let sp50intChart = null;

/**
 * Initialize the dashboard on load
 */
document.addEventListener('DOMContentLoaded', () => {
    initMap();
    initChart();
    loadData(); // Initial load

    // Set up the periodic refresh loop
    setInterval(loadData, REFRESH_INTERVAL);
});

/**
 * Initialize Leaflet Map
 */
function initMap() {
    // Default view: World
    map = L.map('map').setView([20, 0], 2);

    L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png', {
        attribution: '&copy; OpenStreetMap contributors &copy; CARTO'
    }).addTo(map);

    // Layers will be added dynamically when data loads
}

/**
 * Initialize S&P 500 Chart (Placeholder/Mock until real data arrives)
 */
function initChart() {
    const ctx = document.getElementById('sp500Chart').getContext('2d');
    sp5intChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: Array(6).fill(''), // Placeholder labels
            datasets: [{
                label: 'S&P 500 Index',
                data: [], // Data will be injected from JSON
                borderColor: '#ef4444',
                backgroundColor: 'rgba(239, 68, 68, 0.1)',
                fill: true,
                tension: 0.4,
                borderWidth: 2,
                pointRadius: 0
            }]
        },
        options: {
            responsive: true,
            plugins: { legend: { display: false } },
            scales: {
                x: { display: false },
                y: {
                    grid: { color: '#1e293b' },
                    ticks: { color: '#64748b', font: { size: 10 } }
                }
            }
        }
    });
}

/**
 * Core function to fetch and render data
 */
async function loadData() {
    try {
        const response = await fetch(DATA_URL);
        if (!response.ok) throw new Error('Could not fetch data.json');
        const data = await response.json();

        renderNews('news-pl', data.poland);
        renderNews('news-world-security', data.world_security);
        renderNews('news-world-politics', data.world_politics);
        renderNews('news-tech', data.technology);
        renderNews('news-cyber', data.cybersecurity);
        renderNews('news-finance', data.finance);

        renderCriticalAlerts(data.critical_alerts);
        renderInstability(data.instability);
        updateMapLayers(data.map_features);
        updateChart(data.sp500_trend);

        console.log('Dashboard updated:', new Date().toLocaleTimeString());
    } catch (err) {
        console.error('Error loading dashboard data:', err);
        // We don't alert the user to avoid interrupting their viewing,
        // but we could update a status UI element.
    }
}

/**
 * Renders news tiles into specified containers
 * @param {string} containerId - ID of the HTML element
 * @param {Array} articles - Array of article objects
 */
function renderNews(containerId, articles) {
    const container = document.getElementById(containerId);
    if (!container || !articles) return;

    container.innerHTML = ''; // Clear current content

    // Sort by date descending (newest first)
    const sorted = [...articles].sort((a, b) => new Date(b.date) - new Date(a.date));

    sorted.forEach(article => {
        const card = document.createElement('div');
        card.className = 'news-card';

        // Check if article is "new" (within threshold)
        const articleDate = new Date(article.date);
        const now = new Date();
        const diffMins = (now - articleDate) / (1000 * 60);

        if (diffMins < NEW_ARTICLE_THRESHOLD_MINS) {
            card.classList.add('new-article');
        }

        card.innerHTML = `
            <h3 class="news-title">${article.title}</h3>
            <p class="news-snippet">${article.snippet}</p>
            <a href="${article.url}" target="_blank" class="news-link">Czytaj źródło &rarr;</a>
        `;
        container.appendChild(card);
    });
}

/**
 * Renders critical alerts list
 */
function renderCriticalAlerts(alerts) {
    const container = document.getElementById('critical-alerts');
    if (!container || !alerts) return;

    container.innerHTML = alerts.length
        ? alerts.map(a => `<div>• ${a}</div>`).join('')
        : 'Brak krytycznych zagrożeń w tej chwili.';
}

/**
 * Renders instability list
 */
function renderInstability(countries) {
    const container = document.getElementById('country-instability');
    if (!container || !countries) return;

    container.innerHTML = countries.map(c => `
        <div class="instability-item text-sm">
            <span>${c.name}</span>
            <span class="${getRiskClass(c.score)}">${c.score}%</span>
        </div>
    `).join('');
}

function getRiskClass(score) {
    if (score > 70) return 'risk-high';
    if (score > 40) return 'risk-med';
    return 'risk-low';
}

/**
 * Updates Leaflet map with new features/markers
 */
function updateMapLayers(features) {
    if (!map || !features) return;

    // Clear existing layers would be complex without tracking,
    // so for this simple implementation we rely on fresh data loads.
    // In a production app, we'd use a LayerGroup.

    features.forEach(feature => {
        const marker = L.circleMarker([feature.lat, feature.lng], {
            radius: 8,
            fillColor: feature.type === 'war' ? '#ef4444' : '#f59e0b',
            color: "#fff",
            weight: 1,
            opacity: 1,
            fillOpacity: 0.8
        }).addTo(map);

        marker.bindPopup(`<strong>${feature.type.toUpperCase()}</strong><br>${feature.description}`);
    });
}

/**
 * Updates Chart.js with new S&P 50
 */
function updateChart(trendData) {
    if (!sp5intChart || !trendData) return;

    sp5intChart.data.labels = trendData.dates; // e.g. ['Jan', 'Feb'...]
    sp5intChart.data.datasets[0].data = trendData.prices; // e.g. [4200, 4300...]
    sp5intChart.update();
}
